### ISSUE TITLE
query about error rate

### ISSUE THREAD

**Issue by nicholasjhorton** [gyoung19/StatComps#1]
The draft file https://github.com/gyoung19/StatComps/blob/master/SampleJan5th.pdf is shaping up well.  One question: is the 1.26% vs 0.009 just a relic from an earlier seed?

<img width="352" alt="screen shot 2019-01-05 at 5 54 08 pm" src="https://user-images.githubusercontent.com/530542/50726879-5cc55d80-1113-11e9-9abf-b646eeaf84af.png">

**Comment by gyoung19** [comment]
Ah, thank you, I know what that is. I wrote the document on my R Desktop but couldn't compile it to pdf there because of some issue with LaTex, so I copied it over to my Amherst RStudio account to compile the pdf. The same seeds produced different results on the two different platforms and I didn't catch the change is all, I'll work to correct this.
